<?php

namespace App\Filament\Resources\Directories\IncidentTypeResource\Pages;

use App\Filament\Resources\Directories\IncidentTypeResource;
use App\Filament\Resources\Directories\IncidentTypeResource\RelationManagers\ItuCharacteristicsRelationManager;
use App\Filament\Resources\Directories\IncidentTypeResource\RelationManagers\ItuDirectoryObjectsRelationManager;
use App\Filament\Resources\Directories\IncidentTypeResource\RelationManagers\ItuElementsRelationManager;
use App\Filament\Resources\Directories\IncidentTypeResource\RelationManagers\ItuFaultsRelationManager;
use App\Filament\Resources\Directories\IncidentTypeResource\RelationManagers\ItuReasonBreakdownsRelationManager;
use App\Filament\Resources\Directories\IncidentTypeResource\RelationManagers\ItuSpeciesRelationManager;
use App\Models\Directories\IncidentType;
use Filament\Actions;
use Filament\Infolists\Components\Grid;
use Filament\Infolists\Components\IconEntry;
use Filament\Infolists\Infolist;
use Filament\Resources\Pages\ViewRecord;
use Illuminate\Contracts\Support\Htmlable;

class ViewIncidentTypes extends ViewRecord
{
    protected static string $resource = IncidentTypeResource::class;
    protected ?IncidentType $modelRecord;

    public function getTitle(): string|Htmlable
    {
        return 'Тип: ' . $this->record['title'] ?? '';
    }

    public function mount(int|string $record): void
    {
        parent::mount($record); // TODO: Change the autogenerated stub
        $this->modelRecord = $this->record;
    }

    protected function getHeaderActions(): array
    {
        return [
            Actions\EditAction::make()->after(function (IncidentType $record) {
                $this->data = $record->toArray();
            }),
            Actions\DeleteAction::make()
        ];
    }

    public function infolist(Infolist $infolist): Infolist
    {
        return $infolist->schema([
            Grid::make(5)
                ->schema([
                    IconEntry::make('has_species')->label('Наличие видов')->boolean(),
                    IconEntry::make('has_characteristic')->label('Наличие характеристики')->boolean(),
                    IconEntry::make('has_elements')->label('Наличие элементов')->boolean(),
                    IconEntry::make('has_faults')->label('Наличие неисправностей')->boolean(),
                    IconEntry::make('has_directory_objects')->label('Наличие справочника объектов')->boolean(),

                ])
        ]);
    }

    public function getRelationManagers(): array
    {
        $listRelation = [];
        $record = self::getRecord();
        if ($record['has_species']) {
            $listRelation[] = ItuSpeciesRelationManager::class;
        }
        if ($record['has_characteristic']) {
            $listRelation[] = ItuCharacteristicsRelationManager::class;
        }
        if ($record['has_elements']) {
            $listRelation[] = ItuElementsRelationManager::class;
        }
        if ($record['has_faults']) {
            $listRelation[] = ItuFaultsRelationManager::class;
            $listRelation[] = ItuReasonBreakdownsRelationManager::class;
        }
        if ($record['has_directory_objects']) {
            $listRelation[] = ItuDirectoryObjectsRelationManager::class;
        }
        return $listRelation;
    }
}
